export const EDIT_CONTENT = 'EDIT_CONTENT'
export const BLUR_CONTENT = 'BLUR_CONTENT'
export const FOCUS_CONTENT = 'FOCUS_CONTENT'
export const EDIT_CONTENT__AJAX = 'EDIT_CONTENT__AJAX'

export const SWITCH_SPELLCHECK = 'SWITCH_SPELLCHECK'

export const LOGIN__REQUEST = 'LOGIN__REQUEST'
export const LOGIN__SUCCESS = 'LOGIN__SUCCESS'
export const LOGIN__FAILURE = 'LOGIN__FAILURE'

export const CONTENT_PULL__REQUEST = 'CONTENT_PULL__REQUEST'
export const CONTENT_PULL__SUCCESS = 'CONTENT_PULL__SUCCESS'
export const CONTENT_PULL__FAILURE = 'CONTENT_PULL__FAILURE'

export const CONTENT_PUSH__REQUEST = 'CONTENT_PUSH__REQUEST'
export const CONTENT_PUSH__SUCCESS = 'CONTENT_PUSH__SUCCESS'
export const CONTENT_PUSH__FAILURE = 'CONTENT_PUSH__FAILURE'
